# Полный список марок AutoScout24 (актуальный список с сайта)
# Модели будут добавлены постепенно
MAKES = {
    "9FF": [],
    "Abarth": ["500", "595", "695", "Grande Punto"],
    "AC": [],
    "Acura": [],
    "Aiways": ["U5", "U6"],
    "Aixam": [],
    "Alfa Romeo": ["147", "156", "159", "166", "Brera", "Giulia", "Giulietta", "Mito", "Spider", "Stelvio", "Tonale"],
    "Alpina": ["B3", "B4", "B5", "B7", "D3", "D4", "D5"],
    "Alpine": ["A110"],
    "Aston Martin": ["DB9", "DB11", "DBS", "Rapide", "Vantage", "Virage"],
    "Audi": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "Q2", "Q3", "Q3 Sportback", "Q4", "Q5", "Q6", "Q7", "Q8", "R8", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S6", "S7", "S8", "SQ5", "SQ7", "SQ8", "TT", "TTS"],
    "Austin": [],
    "BAIC": ["BJ40", "X55"],
    "BAW": [],
    "Bentley": ["Bentayga", "Continental", "Flying Spur", "Mulsanne"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5", "M6", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4"],
    "Borgward": ["BX5", "BX7"],
    "Brilliance": ["H230", "H320", "V5"],
    "Bugatti": ["Chiron", "Veyron"],
    "Buick": ["Enclave", "Encore", "LaCrosse"],
    "BYD": ["Atto 3", "Dolphin", "Han", "Seal", "Song Plus", "Tang"],
    "Cadillac": ["ATS", "CTS", "Escalade", "SRX", "XT4", "XT5"],
    "Caterham": ["Seven"],
    "Chery": ["Tiggo"],
    "Chevrolet": ["Aveo", "Camaro", "Captiva", "Corvette", "Cruze", "Malibu", "Orlando", "Spark", "Trax", "Volt"],
    "Chrysler": ["300C", "Grand Voyager", "Pacifica", "PT Cruiser", "Sebring", "Voyager"],
    "Citroen": ["Berlingo", "C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "C5 X", "C8", "DS3", "DS4", "DS5", "Jumpy", "Picasso", "SpaceTourer", "Xsara"],
    "Cupra": ["Ateca", "Born", "Formentor", "Leon"],
    "Dacia": ["Bigster", "Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Sandero", "Spring"],
    "Daewoo": ["Kalos", "Lacetti", "Matiz", "Nubira"],
    "Daihatsu": ["Cuore", "Sirion", "Terios", "YRV"],
    "De Tomaso": ["Pantera"],
    "DFSK": ["Glory"],
    "Dodge": ["Caliber", "Challenger", "Charger", "Durango", "Journey", "Nitro", "Ram"],
    "DS Automobiles": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9"],
    "Ferrari": ["458", "488", "California", "F8", "GTC4Lusso", "Portofino", "Roma", "SF90"],
    "Fiat": ["124 Spider", "500", "500L", "500X", "Bravo", "Doblo", "Freemont", "Grande Punto", "Panda", "Punto", "Tipo"],
    "Fisker": ["Karma", "Ocean"],
    "Ford": ["B-Max", "C-Max", "EcoSport", "Edge", "Explorer", "Fiesta", "Focus", "Fusion", "Galaxy", "Grand C-Max", "Kuga", "Mondeo", "Mustang", "Puma", "Ranger", "S-Max", "Tourneo", "Transit"],
    "GAC Gonow": [],
    "GAZ": ["Volga"],
    "Geely": ["Emgrand", "GC6"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "GMC": ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
    "Great Wall": ["Haval H2", "Haval H6", "Steed"],
    "GWM": ["Haval H6", "Ora Funky Cat", "WEY Coffee 01"],
    "Honda": ["Accord", "Civic", "CR-V", "CR-Z", "FR-V", "HR-V", "Insight", "Jazz", "Legend", "NSX"],
    "Hongqi": ["E-HS9", "H5", "H9"],
    "Hummer": ["H1", "H2", "H3"],
    "Hyundai": ["Bayon", "i10", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "Ioniq 6", "ix20", "ix35", "Kona", "Santa Fe", "Sonata", "Staria", "Tucson", "Veloster"],
    "Infiniti": ["FX", "G", "M", "Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX70"],
    "Isuzu": ["D-Max", "Trooper"],
    "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ"],
    "Jeep": ["Cherokee", "Commander", "Compass", "Grand Cherokee", "Renegade", "Wrangler"],
    "KGM": ["Korando", "Musso", "Rexton", "Tivoli"],
    "Kia": ["Carens", "Ceed", "EV6", "Niro", "Optima", "Picanto", "Pro Ceed", "Rio", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Xceed"],
    "Koenigsegg": ["Agera", "Regera"],
    "Lada": ["Granta", "Kalina", "Niva", "Priora", "Vesta", "XRAY"],
    "Lamborghini": ["Aventador", "Huracan", "Urus"],
    "Lancia": ["Delta", "Musa", "Phedra", "Thema", "Ypsilon"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Leapmotor": ["C10", "T03"],
    "Lexus": ["CT", "ES", "GS", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
    "Ligier": [],
    "Lincoln": ["MKC", "MKX", "MKZ", "Navigator"],
    "Lotus": ["Elise", "Evora", "Exige"],
    "Lucid": ["Air"],
    "Lynk & Co": ["01", "02", "03"],
    "Mahindra": ["Scorpio", "XUV500"],
    "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "Quattroporte"],
    "Maybach": ["S-Class", "GLS"],
    "Mazda": ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "RX-8"],
    "McLaren": ["540C", "570S", "600LT", "650S", "720S", "Artura", "GT"],
    "Mercedes-Benz": ["A-Class", "AMG GT", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "S-Class", "SL", "SLK", "V-Class"],
    "MG": ["3", "4", "5", "6", "EHS", "Marvel R", "ZS"],
    "Mini": ["Cabrio", "Clubman", "Countryman", "Coupe", "Hatch", "Paceman", "Roadster"],
    "Mitsubishi": ["ASX", "Colt", "Eclipse Cross", "Grandis", "L200", "Outlander", "Pajero", "Space Star"],
    "Nio": ["ES6", "ES8", "ET5", "ET7"],
    "Nissan": ["350Z", "370Z", "Ariya", "Juke", "Leaf", "Micra", "Murano", "Navara", "Note", "Pathfinder", "Qashqai", "X-Trail"],
    "Opel": ["Adam", "Agila", "Antara", "Astra", "Cascada", "Corsa", "Crossland", "Grandland", "Insignia", "Meriva", "Mokka", "Omega", "Signum", "Vectra", "Vivaro", "Zafira"],
    "ORA": ["Funky Cat"],
    "Peugeot": ["107", "108", "2008", "206", "207", "208", "3008", "301", "307", "308", "4007", "4008", "407", "5008", "508", "Rifter", "Traveller"],
    "Polestar": ["1", "2", "3", "4"],
    "Porsche": ["718", "911", "Boxster", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
    "Renault": ["Arkana", "Austral", "Captur", "Clio", "Espace", "Fluence", "Kadjar", "Kangoo", "Laguna", "Megane", "Modus", "Scenic", "Talisman", "Twingo", "Zoe"],
    "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Silver Shadow", "Wraith"],
    "Saab": ["9-3", "9-5"],
    "Seat": ["Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Exeo", "Ibiza", "Leon", "Tarraco", "Toledo"],
    "Seres": ["3", "5"],
    "Silence": ["S04"],
    "Skoda": ["Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Roomster", "Scala", "Superb", "Yeti"],
    "Smart": ["EQ Fortwo", "Forfour", "Fortwo", "Roadster"],
    "Ssangyong": ["Korando", "Musso", "Rexton", "Tivoli", "XLV"],
    "Subaru": ["BRZ", "Forester", "Impreza", "Legacy", "Levorg", "Outback", "XV"],
    "Suzuki": ["Alto", "Baleno", "Grand Vitara", "Ignis", "Jimny", "Liana", "Splash", "Swift", "SX4", "Vitara"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
    "Toyota": ["Auris", "Avensis", "Aygo", "C-HR", "Camry", "Corolla", "GR86", "GR Supra", "Highlander", "Land Cruiser", "Prius", "Prius Plus", "RAV4", "Urban Cruiser", "Verso", "Yaris", "Yaris Cross"],
    "VinFast": ["VF 8", "VF 9"],
    "Volkswagen": ["Amarok", "Arteon", "Beetle", "Caddy", "CC", "Eos", "Golf", "Golf Plus", "Golf Sportsvan", "ID.3", "ID.4", "ID.5", "Jetta", "Passat", "Phaeton", "Polo", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Transporter", "Up"],
    "Volvo": ["C30", "C40", "C70", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
    "WEY": ["Coffee 01", "Coffee 02"],
    "XEV": ["YOYO"],
    "Xpeng": ["G3", "G6", "G9", "P5", "P7"],
}
